### PR TITLE
SLING-10384: Execute actions before sending "o/a/s/d/i/package/import…

### PR DESCRIPTION
**Pull request by amit-jain**
…ed" event

- Add an interface and exception to act as import post processor

### CODE REVIEW

**Review by tmaret — APPROVED** [review]

**Comment by amit-jain** [comment]
Thanks @tmaret & @joerghoh 
Could you please commit the changes and create a new release as it needs to be updated in the journal bundle.

**Comment by tmaret** [comment]
We'd need to remove the `IMPORTER_PACKAGE_COMMITTED` field introduced [here](https://github.com/apache/sling-org-apache-sling-distribution-api/commit/915a638ba3be7ed5ef36ddb0d3daa1d530217833#diff-0b7d2c076ac2b3e65c30a83f81f3fda0155d1128783545ebbf07a86b9fe43169R59) before cutting a release.

@amit-jain could you remove the field in this PR ?

CC @joerghoh

**Comment by tmaret** [comment]
Thanks @amit-jain ! LGTM

**Comment by joerghoh** [comment]
thanks @amit-jain  for your contribution!

**Pull request merged**
